Repository authsignal/authsignal-android, pull requests merged in 2025-08, with the labels that each got.

#55 Handle 404 if no error response provided
  README.md
  module/gradle.properties
  module/src/main/java/com/authsignal/APIError.kt
  module/src/main/java/com/authsignal/models/UserActionState.kt
Labels: documentation

#57 Persistence of default device ID for passkey auth
  module/gradle.properties
  module/src/main/java/com/authsignal/passkey/AuthsignalPasskey.kt
Labels: bug

#58 Bump versions for gradle, agp, credentials
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  module/build.gradle.kts
  module/gradle.properties
  module/src/main/java/com/authsignal/passkey/AuthsignalPasskey.kt
Labels: enhancement, alpha

#60 Handle passkey dom exception on create
  module/gradle.properties
  module/src/main/java/com/authsignal/passkey/PasskeyManager.kt
Labels: enhancement

#61 Make params optional in AuthsignalPasskey ctor
  module/gradle.properties
  module/src/main/java/com/authsignal/passkey/AuthsignalPasskey.kt
Labels: bug

#65 Add shouldPromptToCreatePasskey method
  module/gradle.properties
  module/src/main/java/com/authsignal/APIError.kt
  module/src/main/java/com/authsignal/passkey/AuthsignalPasskey.kt
  module/src/main/java/com/authsignal/passkey/PasskeyManager.kt
Labels: enhancement
